import os

APP_VERSION = '0.0.1'
DEBUG = True
PROPOGATE_EXCEPTIONS = True
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_SECRET_KEY = os.environ.get('JWT_SECRET_KEY', '_5#y2L"F4Q8z]/')
